# Site settings
title: Mastering Xamarin
header-img: img/cebu-sunset.jpg
email: jaeyow@gmail.com
copyright_name: Jose Reyes
description: "For all things Xamarin"
baseurl: ""
url: "http://masteringxamarin.com"
twitter_username: JaeyowReyes
github_username:  jaeyow
facebook_username:  jaeyow
email_username:  jaeyow@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
#rdiscount:
#  extensions: [smart]
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]  
gems: [jekyll-paginate, jekyll-feed]
